# render.yaml (Production Ready)
services:
  - type: web
    name: backend
    env: node
    nodeVersion: 18.16.0
    rootDirectory: backend
    buildCommand: |
      npm install
      npx prisma generate
      npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 7000 

  - type: static
    name: frontend
    rootDirectory: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    addHeaders:
      - name: Content-Security-Policy
        value: "default-src 'self' https: 'unsafe-inline'" 
    envVars:
      - key: VITE_API_URL
        value: https://your-backend-service.onrender.com  # REPLACE WITH ACTUAL URL

cache:
  directories:
    - backend/node_modules
    - frontend/node_modules

autoDeploy: true